ages <- c(13, 15, 16, 16, 19, 20, 20, 21, 22, 22, 25, 25, 25, 25, 30, 33, 33, 35, 35, 35, 35, 36, 40, 45, 46, 52, 70)
mean_age <- mean(ages)
median_age <- median(ages)
mode_age <- as.numeric(names(sort(table(ages), decreasing = TRUE)[1]))
frequency_table <- table(ages)
modes <- names(frequency_table[frequency_table == max(frequency_table)])
modality <- length(modes)
midrange_age <- (min(ages) + max(ages)) / 2
Q1 <- quantile(ages, 0.25)
Q3 <- quantile(ages, 0.75)
cat("Mean of the data is:", mean_age, "\n")
cat("Median of the data is:", median_age, "\n")
cat("Mode of the data is:", mode_age, "\n")
cat("The data's modality is:", ifelse(modality == 1, "unimodal", ifelse(modality == 2, "bimodal", paste(modality, "modes"))), "\n")
cat("Midrange of the data is:", midrange_age, "\n")
cat("First quartile (Q1) of the data is:", Q1, "\n")
cat("Third quartile (Q3) of the data is:", Q3, "\n")
